/**
 * Parity against PyTorch.
 *
 * The fixture is generated by `scripts/export_web_model.py` in the MAPF-GNN
 * repository, from the same checkpoint the browser loads. It records the field
 * of view, the communication graph, the logits, the actions and the positions
 * at every step of a short deterministic rollout, so a failure says *which*
 * stage diverged instead of just that the demo is wrong.
 *
 * The instance is deliberately crowded: on a sparse board the communicating and
 * non-communicating policies choose identical actions, so this would pass for an
 * implementation that never looked at the graph.
 *
 * Run with:  npx tsx src/components/mapf/test/parity.ts
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { MapfEnv } from '../env';
import { Policy } from '../policy';
import { parseModel } from '../weights';
import type { DemoManifest, Instance } from '../types';

const ASSETS = join(process.cwd(), 'public', 'assets', 'models', 'mapf');
const LOGIT_TOLERANCE = 1e-3;
const FLOAT_TOLERANCE = 1e-5;

interface FixtureStep {
    positions: number[][];
    fov?: number[][][][];
    adjacency?: number[][];
    logits?: number[][];
    actions?: number[];
}

interface Fixture {
    board: number;
    num_agents: number;
    sensing_range: number;
    obstacles: Array<[number, number]>;
    starts: Array<[number, number]>;
    goals: Array<[number, number]>;
    models: Record<string, { steps: FixtureStep[] }>;
}

/** Node hands back a Buffer that may be a window into a larger pool. */
function readBuffer(name: string): ArrayBuffer {
    const raw = readFileSync(join(ASSETS, name));
    return raw.buffer.slice(raw.byteOffset, raw.byteOffset + raw.byteLength) as ArrayBuffer;
}

function readJson<T>(name: string): T {
    return JSON.parse(readFileSync(join(ASSETS, name), 'utf8')) as T;
}

let failures = 0;
let checks = 0;

function report(label: string, worst: number, tolerance: number, detail = ''): void {
    checks++;
    const ok = worst <= tolerance;
    if (!ok) failures++;
    const status = ok ? 'ok  ' : 'FAIL';
    const suffix = detail ? `  ${detail}` : '';
    console.log(`  ${status} ${label.padEnd(34)} worst ${worst.toExponential(2)}${suffix}`);
}

function maxAbsDiff(actual: ArrayLike<number>, expected: number[]): number {
    let worst = 0;
    for (let i = 0; i < expected.length; i++) {
        worst = Math.max(worst, Math.abs(actual[i] - expected[i]));
    }
    return worst;
}

function main(): void {
    const manifest = readJson<DemoManifest>('config.json');
    const fixture = readJson<Fixture>('fixture.json');

    const instance: Instance = {
        board: fixture.board,
        obstacles: fixture.obstacles,
        starts: fixture.starts,
        goals: fixture.goals,
    };

    console.log(
        `fixture: ${fixture.num_agents} robots on ${fixture.board}x${fixture.board}, ` +
        `${fixture.obstacles.length} obstacles, sensing range ${fixture.sensing_range}`
    );

    for (const [name, modelManifest] of Object.entries(manifest.models)) {
        const model = parseModel(modelManifest, readBuffer(modelManifest.file));
        const steps = fixture.models[name].steps;

        console.log(`\n${name} (${model.arch}, ${model.parameters.toLocaleString()} parameters)`);

        const env = new MapfEnv(
            {
                board: fixture.board,
                sensingRange: manifest.sensing_range,
                pad: manifest.pad,
                maxNeighbours: manifest.max_neighbours,
            },
            instance
        );
        const policy = new Policy(model, fixture.num_agents, manifest.fov[0]);

        let worstFov = 0;
        let worstAdjacency = 0;
        let worstLogits = 0;
        let worstPositions = 0;
        let actionMismatches = 0;
        let totalActions = 0;

        for (let t = 0; t < steps.length; t++) {
            const step = steps[t];

            worstPositions = Math.max(worstPositions, maxAbsDiff(
                flattenPairs(env.posX, env.posY),
                step.positions.flat()
            ));

            if (!step.actions) break;

            worstFov = Math.max(worstFov, maxAbsDiff(env.fov, (step.fov as number[][][][]).flat(3)));
            worstAdjacency = Math.max(worstAdjacency, maxAbsDiff(
                env.adjacency,
                (step.adjacency as number[][]).flat()
            ));

            const logits = policy.forward(env.fov, env.adjacency);
            worstLogits = Math.max(worstLogits, maxAbsDiff(logits, (step.logits as number[][]).flat()));

            const actions = policy.selectActions(0, null);
            for (let i = 0; i < actions.length; i++) {
                totalActions++;
                if (actions[i] !== step.actions[i]) actionMismatches++;
            }

            env.step(actions);
        }

        report('field of view', worstFov, FLOAT_TOLERANCE);
        report('adjacency', worstAdjacency, FLOAT_TOLERANCE);
        report('logits', worstLogits, LOGIT_TOLERANCE);
        report('actions', actionMismatches, 0, `${totalActions - actionMismatches}/${totalActions} match`);
        report('positions', worstPositions, 0, `${steps.length} steps`);
    }

    // A demo that ignored the communication graph would still pass everything
    // above if the two policies happened to agree, so confirm they do not.
    const commActions = collectActions(fixture, 'comm');
    const nocommActions = collectActions(fixture, 'nocomm');
    const differing = commActions.filter((a, i) => a !== nocommActions[i]).length;
    console.log(
        `\nfixture discriminates: ${differing}/${commActions.length} actions differ ` +
        'between the communicating and non-communicating policies'
    );
    if (differing === 0) {
        failures++;
        console.log('  FAIL the fixture cannot detect a missing communication path');
    }

    console.log(`\n${failures === 0 ? 'PASS' : 'FAIL'} — ${checks} checks, ${failures} failed`);
    process.exit(failures === 0 ? 0 : 1);
}

function collectActions(fixture: Fixture, name: string): number[] {
    return fixture.models[name].steps.flatMap(step => step.actions ?? []);
}

function flattenPairs(xs: Int32Array, ys: Int32Array): number[] {
    const out: number[] = [];
    for (let i = 0; i < xs.length; i++) out.push(xs[i], ys[i]);
    return out;
}

main();
